language: node_js


node_js:
   - node # will use latest node

before_script: # commands to run before the build step
    - cd ./angular && npm install -g --silent @angular/cli

script: # the build step
 
   - cd ./angular && ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive # firebase deploy after angular-cli build

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change   

    